import type { CuratedGame } from '../types';

export const GAMES_LIBRARY: CuratedGame[] = [
  // ═══════════════ DOMINÓ ═══════════════
  {
    id: 'domino-normal',
    name: 'Dominó',
    category: 'Dominó',
    description: 'O clássico jogo de peças com pipas',
    rulesText: `• Cada jogador recebe 7 peças (ou 5 em alguns modos)\n• O objetivo é ser o primeiro a usar todas as suas peças\n• Quem fechar a rodada conta os pontos das peças dos adversários\n• Se a partida travar, vence quem tiver menor soma de pipas\n• Pontuação: soma das pipas dos perdedores em cada rodada`,
    tags: ['peças', 'clássico', 'familiar'],
    playerCount: '2–4 jogadores',
    duration: '20–45 min',
    config: {
      themeColor: '#475569',
      victoryCondition: 'highest_score',
      winningScore: 100,
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'layers',
    },
  },
  {
    id: 'domino-burrinho',
    name: 'Dominó Burrinho',
    category: 'Dominó',
    description: 'Quem atingir a pontuação limite é o burrinho!',
    rulesText: `• Cada jogador recebe 7 peças\n• Quem fechar a rodada marca 0 pontos\n• Os demais contam a soma das pipas que sobraram\n• Perde o jogo quem atingir 50 pontos\n• Variante popular no interior do Brasil — ótimo para grupos`,
    tags: ['peças', 'clássico', 'familiar'],
    playerCount: '2–4 jogadores',
    duration: '20–40 min',
    config: {
      themeColor: '#64748b',
      victoryCondition: 'lowest_score',
      winningScore: 50,
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'layers',
    },
  },

  // ═══════════════ TRUCO ═══════════════
  {
    id: 'truco-paulista',
    name: 'Truco Paulista',
    category: 'Truco',
    description: 'Truco tradicional de São Paulo, dupla a dupla',
    rulesText: `• Disputado em duplas (2 times de 2 jogadores)\n• Cada rodada vale 1 ponto, podendo ser trucada\n• Truco: vale 3 | Re-truco: vale 6 | Doze: vale 12\n• Manilhas em ordem: Zap (♣4), Copas (♥4), Espadão (♠4), Ouros (♦4)\n• Mãos de 10-10 (mão de onze): vale 3 pts na próxima rodada\n• Vence quem atingir 12 pontos primeiro`,
    tags: ['cartas', 'times', 'brasileiro', 'blefe'],
    playerCount: '4 jogadores (2 times)',
    duration: '30–60 min',
    config: {
      themeColor: '#dc2626',
      victoryCondition: 'highest_score',
      winningScore: 12,
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'spade',
    },
  },
  {
    id: 'truco-mineiro',
    name: 'Truco Mineiro',
    category: 'Truco',
    description: 'Truco de Minas Gerais com bara e cocó',
    rulesText: `• Disputado em duplas (2 times de 2 jogadores)\n• Truco: vale 3 | Seis: 6 | Nove: 9 | Doze: 12\n• Manilhas fixas (sem virar baralho): 7♥, 7♦, A♠, A♣\n• Bara e Cocó: se um time está em 11 pts, adversário vê as cartas\n• Vence quem atingir 12 pontos primeiro`,
    tags: ['cartas', 'times', 'brasileiro', 'blefe'],
    playerCount: '4 jogadores (2 times)',
    duration: '30–60 min',
    config: {
      themeColor: '#b91c1c',
      victoryCondition: 'highest_score',
      winningScore: 12,
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'spade',
    },
  },

  // ═══════════════ CARTAS ═══════════════
  {
    id: 'buraco',
    name: 'Buraco',
    category: 'Cartas',
    description: 'Jogo de canastas com dois baralhos para duplas',
    rulesText: `• Jogado em duplas com 2 baralhos completos (108 cartas)\n• Objetivo: formar canastas (grupos de 7+ cartas iguais)\n• Canasta limpa (sem curinga): +200 pts | Suja (com curinga): +100 pts\n• Buraco (fechar a mão sem pegar do monte): bônus +100 pts\n• Cartas na mão ao terminar: pontuação negativa (valor da carta)\n• Vence quem atingir 3000 pontos ou mais`,
    tags: ['cartas', 'times', 'clássico', 'brasileiro'],
    playerCount: '4 jogadores (2 times)',
    duration: '45–90 min',
    config: {
      themeColor: '#2563eb',
      victoryCondition: 'highest_score',
      winningScore: 3000,
      allowNegative: true,
      scoringMode: 'numeric',
      icon: 'clubs',
    },
  },
  {
    id: 'canastra',
    name: 'Canastra',
    category: 'Cartas',
    description: 'Clássico jogo de canastas com baralho duplo',
    rulesText: `• Jogado em duplas com 2 baralhos completos\n• Canasta limpa: +500 pts | Suja: +300 pts | Real (com A): +1000 pts\n• Para fechar: precisa de ao menos 1 canasta + descartar última carta\n• Fechamento limpo: bônus +100 pts | Sujo: sem bônus\n• Saída exige mínimo de 50/90/120 pts de cartas em jogo\n• Vence quem atingir 5000 pontos`,
    tags: ['cartas', 'times', 'clássico', 'brasileiro'],
    playerCount: '4 jogadores (2 times)',
    duration: '60–120 min',
    config: {
      themeColor: '#7c3aed',
      victoryCondition: 'highest_score',
      winningScore: 5000,
      allowNegative: true,
      scoringMode: 'numeric',
      icon: 'clubs',
    },
  },
  {
    id: 'phase-10',
    name: 'Phase 10',
    category: 'Cartas',
    description: 'Complete as 10 fases antes dos adversários',
    rulesText: `• Cada jogador completa as 10 fases em ordem crescente\n• Cada fase exige combinações específicas (sequências ou grupos)\n• Quem não completar a fase conta os pontos das cartas na mão\n• Cartas numéricas: valor nominal | Pulos e Coringas: 25 pts\n• 10 rodadas fixas — uma por fase\n• Vence quem completar a fase 10 com menos pontos acumulados`,
    tags: ['cartas', 'familiar', 'fases'],
    playerCount: '2–6 jogadores',
    duration: '45–75 min',
    config: {
      themeColor: '#d97706',
      victoryCondition: 'lowest_score',
      allowNegative: false,
      scoringMode: 'numeric',
      maxRounds: 10,
      icon: 'flag',
    },
  },
  {
    id: 'love-letter',
    name: 'Love Letter',
    category: 'Cartas',
    description: 'Jogo de dedução com apenas 16 cartas',
    rulesText: `• Cada jogador tem 1 carta na mão + compra 1 por turno, joga 1\n• Cartas ativam habilidades: espiar, eliminar, proteger, etc.\n• Último sobrevivente ou maior valor ao final vence a rodada\n• Vencedor da rodada recebe 1 token de amor\n• Vence quem atingir: 7 tokens (2 jog.), 5 tokens (3 jog.), 4 tokens (4 jog.)`,
    tags: ['cartas', 'dedução', 'rápido'],
    playerCount: '2–4 jogadores',
    duration: '15–25 min',
    config: {
      themeColor: '#e11d48',
      victoryCondition: 'highest_score',
      winningScore: 7,
      allowNegative: false,
      scoringMode: 'winner_takes_all',
      icon: 'heart',
    },
  },
  {
    id: 'coup',
    name: 'Coup',
    category: 'Cartas',
    description: 'Blefe, golpes e eliminação em um jogo de poder',
    rulesText: `• Cada jogador começa com 2 cartas de personagem secretas e 2 moedas\n• Declare ações usando qualquer personagem (mesmo que não tenha a carta)\n• Oponentes podem desafiar ou bloquear suas ações\n• Perder um desafio ou sofrer um golpe certo: perde 1 influência (carta virando)\n• Perde as 2 influências: está eliminado do jogo\n• Último sobrevivente vence — não há pontuação acumulada`,
    tags: ['cartas', 'blefe', 'social', 'rápido'],
    playerCount: '2–6 jogadores',
    duration: '15–30 min',
    config: {
      themeColor: '#b45309',
      victoryCondition: 'highest_score',
      allowNegative: false,
      scoringMode: 'winner_takes_all',
      icon: 'crown',
    },
  },

  // ═══════════════ ESTRATÉGIA ═══════════════
  {
    id: 'ticket-to-ride',
    name: 'Ticket to Ride',
    category: 'Estratégia',
    description: 'Conecte cidades com rotas ferroviárias e complete missões',
    rulesText: `• Colete cartas de trem para construir rotas no mapa\n• Pontos por rota: 1→1, 2→2, 3→4, 4→7, 5→10, 6→15\n• Complete bilhetes de destino para bônus de pontos\n• Bilhetes não completados ao final: pontuação negativa equivalente\n• Caminho mais longo contínuo: bônus de +10 pts\n• Jogo termina quando algum jogador ficar com 2 ou menos vagões`,
    tags: ['estratégia', 'rotas', 'mapa', 'família'],
    playerCount: '2–5 jogadores',
    duration: '45–75 min',
    config: {
      themeColor: '#dc2626',
      victoryCondition: 'highest_score',
      allowNegative: true,
      scoringMode: 'numeric',
      icon: 'map',
    },
  },
  {
    id: 'splendor',
    name: 'Splendor',
    category: 'Estratégia',
    description: 'Colete gemas e construa seu império comercial',
    rulesText: `• Colete fichas de gemas e compre cartas de desenvolvimento\n• Cartas dão bônus permanentes que reduzem o custo de compras futuras\n• Nobres concedem 3 pts automaticamente ao cumprir requisitos de bônus\n• Você pode reservar 1 carta por turno (recebe 1 ficha de ouro curinga)\n• Fichas de ouro substituem qualquer gema na compra\n• Vence quem atingir 15 pontos de prestígio ao fim do turno`,
    tags: ['estratégia', 'engine-building', 'família'],
    playerCount: '2–4 jogadores',
    duration: '30–45 min',
    config: {
      themeColor: '#0891b2',
      victoryCondition: 'highest_score',
      winningScore: 15,
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'gem',
    },
  },
  {
    id: '7-wonders',
    name: '7 Wonders',
    category: 'Estratégia',
    description: 'Construa uma civilização em 3 eras de drafting',
    rulesText: `• O jogo tem 3 eras, cada uma com 6 rodadas de drafting de cartas\n• Por turno: jogue 1 carta, descarte por 3 moedas, ou use para avançar sua maravilha\n• Pontos vêm de: cartas civis, comerciais, militares, científicas e maravilhas\n• Ao fim de cada era: compare força militar com os vizinhos\n• Ciência: pontos exponenciais por símbolos iguais + bônus por conjuntos\n• Vence quem tiver mais pontos ao final das 3 eras`,
    tags: ['estratégia', 'drafting', 'civilização'],
    playerCount: '2–7 jogadores',
    duration: '30–45 min',
    config: {
      themeColor: '#b45309',
      victoryCondition: 'highest_score',
      allowNegative: true,
      scoringMode: 'numeric',
      maxRounds: 3,
      icon: 'layers',
    },
  },
  {
    id: 'carcassonne',
    name: 'Carcassonne',
    category: 'Estratégia',
    description: 'Construa paisagens medievais com peças de terreno',
    rulesText: `• Por turno: retire 1 peça e coloque no mapa adjacente a outra\n• Você pode colocar 1 meeple (seguidor) na peça jogada\n• Cidades completas: 2 pts/peça + 2 pts/escudo\n• Estradas completas: 1 pt por peça | Mosteiro completo: 9 pts\n• Cidades/estradas incompletas ao final: 1 pt/peça\n• Campos (ao final): 3 pts por cidade completa adjacente`,
    tags: ['estratégia', 'tile-placement', 'medieval'],
    playerCount: '2–5 jogadores',
    duration: '35–50 min',
    config: {
      themeColor: '#15803d',
      victoryCondition: 'highest_score',
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'map',
    },
  },
  {
    id: 'kingdomino',
    name: 'Kingdomino',
    category: 'Estratégia',
    description: 'Monte seu reino 5×5 com dominós de terrenos',
    rulesText: `• Cada dominó tem 2 terrenos; alguns têm coroas\n• Monte um reino de no máximo 5×5 peças conectando terrenos iguais\n• Pontuação: área do reino × número de coroas presentes\n• Bônus: reino 5×5 perfeito (+5 pts) | Castelo no centro (+5 pts)\n• Ordem de turno determinada pela peça escolhida na rodada anterior\n• Jogo dura 12 rodadas (48 peças ÷ 4 jogadores)`,
    tags: ['estratégia', 'tile-placement', 'família', 'rápido'],
    playerCount: '2–4 jogadores',
    duration: '15–25 min',
    config: {
      themeColor: '#16a34a',
      victoryCondition: 'highest_score',
      allowNegative: false,
      scoringMode: 'numeric',
      maxRounds: 12,
      icon: 'crown',
    },
  },

  // ═══════════════ SOCIAL / PARTY ═══════════════
  {
    id: 'dixit',
    name: 'Dixit',
    category: 'Social',
    description: 'Narrativas com ilustrações surreais e imaginação',
    rulesText: `• O narrador da rodada escolhe 1 carta e diz uma dica (palavra, frase ou som)\n• Todos os outros jogam 1 carta que se encaixe na dica\n• Todos votam em qual carta pertence ao narrador\n• Se todos ou ninguém adivinhar: narrador fica sem ponto\n• Quem adivinhou: +3 pts | Narrador (acertaram de 1 a n-1): +3 pts\n• Por cada voto recebido em sua carta: +1 pt | Vence com 30 pts`,
    tags: ['social', 'criatividade', 'família', 'party'],
    playerCount: '3–6 jogadores',
    duration: '30–45 min',
    config: {
      themeColor: '#7c3aed',
      victoryCondition: 'highest_score',
      winningScore: 30,
      allowNegative: false,
      scoringMode: 'numeric',
      icon: 'sparkles',
    },
  },
  {
    id: 'sushi-go',
    name: 'Sushi Go!',
    category: 'Social',
    description: 'Drafting de cartas de sushi em 3 rodadas',
    rulesText: `• 3 rodadas de drafting: escolha 1 carta e passe o resto para o lado\n• Niguiri: 1-3 pts | Com wasabi: triplica o próximo niguiri adquirido\n• Tempurá: 5 pts por par de 2 cartas | Sashimi: 10 pts por trio de 3\n• Gyoza: 1/3/6/10/15 pts conforme quantidade\n• Pudim (acumulado nas 3 rodadas): mais → +6 pts | menos → −6 pts\n• Vence quem tiver mais pontos ao fim das 3 rodadas`,
    tags: ['social', 'drafting', 'família', 'rápido'],
    playerCount: '2–5 jogadores',
    duration: '15–20 min',
    config: {
      themeColor: '#db2777',
      victoryCondition: 'highest_score',
      allowNegative: true,
      scoringMode: 'numeric',
      maxRounds: 3,
      icon: 'star',
    },
  },
  {
    id: 'dobble',
    name: 'Dobble / Spot It',
    category: 'Social',
    description: 'Encontre o símbolo em comum entre duas cartas',
    rulesText: `• Sempre existe exatamente 1 símbolo em comum entre 2 cartas quaisquer\n• Modos de jogo: Torre (empilha), Quente-Fria (quem tiver menos vence), Fogo-Cruzado\n• Vence quem coletar mais cartas (ou menos, dependendo do modo)\n• Jogo puro de reflexo e percepção visual\n• Ótimo para aquecer o grupo antes de jogos mais complexos`,
    tags: ['social', 'reflexo', 'party', 'rápido', 'família'],
    playerCount: '2–8 jogadores',
    duration: '10–15 min',
    config: {
      themeColor: '#f59e0b',
      victoryCondition: 'highest_score',
      allowNegative: false,
      scoringMode: 'winner_takes_all',
      icon: 'target',
    },
  },
  {
    id: 'codenames',
    name: 'Codenames',
    category: 'Social',
    description: 'Descubra os agentes da sua equipe com dicas de 1 palavra',
    rulesText: `• 2 times: cada um tem um espião-mestre que conhece o mapa secreto\n• Espião dá uma dica: 1 palavra + número de cartas relacionadas\n• Time tenta identificar as cartas que correspondem à dica\n• Acertar agente inimigo: turno passa para o adversário\n• Acertar o Assassino: derrota imediata para o time!\n• Vence o primeiro time a encontrar todos os seus agentes (8 ou 9)`,
    tags: ['social', 'times', 'palavras', 'party'],
    playerCount: '4–8 jogadores',
    duration: '15–30 min',
    config: {
      themeColor: '#1d4ed8',
      victoryCondition: 'highest_score',
      allowNegative: false,
      scoringMode: 'winner_takes_all',
      icon: 'shield',
    },
  },

  // ═══════════════ DADOS ═══════════════
  {
    id: 'yatzy',
    name: 'Yatzy / Yahtzee',
    category: 'Dados',
    description: 'Complete combinações de dados em categorias fixas',
    rulesText: `• Cada turno: até 3 lançamentos de 5 dados (pode manter dados entre rolagens)\n• Escolha uma categoria para registrar o resultado (cada uma usável 1x)\n• Yatzy / Yahtzee (5 dados iguais): 50 pts especiais\n• Seções 1-6: soma dos dados do número correspondente\n• Bônus superior: ≥ 63 pts nas seções 1-6 = +35 pts extras\n• Jogo tem exatamente 13 rodadas (uma por categoria)`,
    tags: ['dados', 'clássico', 'família'],
    playerCount: '1–6 jogadores',
    duration: '20–35 min',
    config: {
      themeColor: '#ca8a04',
      victoryCondition: 'highest_score',
      allowNegative: false,
      scoringMode: 'numeric',
      maxRounds: 13,
      icon: 'dice1',
    },
  },
];

/** IDs únicos de categorias na ordem em que aparecem */
export const LIBRARY_CATEGORIES = [...new Set(GAMES_LIBRARY.map(g => g.category))];

/** ID definitivo do GameConfig gerado a partir de um jogo da biblioteca */
export const getLibraryGameId = (curatedId: string) => `lib_${curatedId}`;

/** Busca por nome, categoria, descrição ou tags */
export const searchLibrary = (query: string): CuratedGame[] => {
  if (!query.trim()) return GAMES_LIBRARY;
  const q = query.toLowerCase();
  return GAMES_LIBRARY.filter(g =>
    g.name.toLowerCase().includes(q) ||
    g.category.toLowerCase().includes(q) ||
    g.description.toLowerCase().includes(q) ||
    g.tags.some(t => t.toLowerCase().includes(q))
  );
};
